### ISSUE TITLE
Time zones are wrong

### ISSUE THREAD

**Issue by gpmcadam** [timefyi/time.fyi#14] opened 2024-03-27 12:14 UTC
Not sure if this is still maintained but the time zones displayed are currently wrong.

Los Angeles, New York etc. are not GMT-8 or -5 respectively, as they are on daylight savings, so they are UTC-7 or -4

URL:

https://time.fyi/timezones?d=America%2FLos_Angeles%3Dx%3DLos%20Angeles%2CAmerica%2FNew_York%3Dx%3DBoston%2CEurope%2FLondon-primary%2CEurope%2FBelgrade%3Dy%3DSerbia%2CAsia%2FManila%3Dy%3DPhilippines%2CAmerica%2FSao_Paulo&t=

<img width="1297" alt="image" src="https://github.com/timefyi/time.fyi/assets/17268999/fcdaf991-e0bc-4a10-89b9-8c2f86ec2f4b">

Also if I go forward in time I would expect to see the daylight savings differences taken into account. For example, London is not in DST at the time of writing, but on Sunday 31st March it will enter BST (GMT+1)

But this doesn't seem to be taken into account

**Comment by pepve** [comment] 2024-03-31 10:36
I ran into this too. At least part of the problem is that whole timezone objects are stored in local storage including the gmt offset. And the displayed gmt offset is take from there. That approach doesn't work because the gmt offset changes of course.

So adding a timezone before DST and then adding the same timezone after DST gives you this:

![Screenshot 2024-03-31 at 12-31-38 time fyi - timezones](https://github.com/timefyi/time.fyi/assets/823248/19f8fd63-1e4e-4ba3-9c4f-01b56560fae2)

**Comment by nilbuild** [comment] 2024-03-31 13:25
I just deployed a fix for this. 
Let me know if you still face any issues.


<img width="698" alt="image" src="https://github.com/timefyi/time.fyi/assets/4921183/2b0de2b5-e729-40f3-9c0b-63411e75f6ac">

<img width="689" alt="image" src="https://github.com/timefyi/time.fyi/assets/4921183/57b3029d-d784-4b0f-a7e7-f62b56fe9d48">

**Closed as completed by nilbuild** 2024-03-31 13:25 UTC
Labels: bug

**Comment by pepve** [comment] 2024-03-31 16:51
There's still stale data displayed, let me know if this should be a new bug.

Clear browser state, add Detroit, set date to March 10 and time to 3:00 AM:

![Screenshot 2024-03-31 at 18-38-02 time fyi - timezones](https://github.com/timefyi/time.fyi/assets/823248/2a294802-ec81-4c10-b835-164ea0b479ab)

The gmt offset and timezone abbreviation are shown correctly. Now drag the slider back 15 minutes:

![Screenshot 2024-03-31 at 18-38-44 time fyi - timezones](https://github.com/timefyi/time.fyi/assets/823248/2a773012-d9f5-4334-b2db-f7202b7abce9)

The time changes correctly to 1:45 AM, and the gmt offset is shown correctly, but the timezone abbreviation still says EDT. It should say EST.

I think the only thing you can really persist is the timezone id. All of the other timezone data will change sooner or later.

**Comment by nilbuild** [comment] 2024-04-01 01:01
This has been fixed. Thank you for reporting.

https://github.com/timefyi/time.fyi/assets/4921183/259c095f-e860-490e-bf07-d2132fd38577

Also hovering the card now shows the timezone name

<img width="749" alt="image" src="https://github.com/timefyi/time.fyi/assets/4921183/ce306d59-027e-4ee3-b593-053c85b377b2">

Let me know if you still face any issues 🙏
